### ISSUE TITLE
Pull Access Denied

### ISSUE THREAD

**Issue by jtumah** [michaelhaessig/wordpress-stateless#1]
I am trying to deploy wordpress GCE with kubernetes using your instructions but there seems to be a hitch. When I run the following command in the sample folder I get an error copied below;
$ sudo docker build -t eu.gcr.io/oxygen-o2/my-wordpress .

error:
Sending build context to Docker daemon  408.6MB
Step 1/100 : FROM wp-stateless-nginx:wp-4.7.5
pull access denied for wp-stateless-nginx, repository does not exist or may require 'docker login'

**Comment by michaelhaessig** [comment]
Do I understand correctly, you are trying to build you docker container locally, tag and then upload to google cloud registry ? 
The FROM instruction has to point to an image that exist. To use the wordpress-stateless images from this repository you first have to build the images yourself with the 'build-images.sh' script in to root directory of the repo. After you have built the images adjust the tag version and trigger you image build in the sample folder.
